# Generated by Django 5.1.3 on 2026-01-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Testapp", "0004_alter_studentinfo_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentinfo",
            name="image",
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="address",
            field=models.CharField(max_length=78),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="name",
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
